name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --no-audit

    - name: Build the project
      id: build
      run: npm run build || exit 1  
      env:
        NODE_OPTIONS: --max_old_space_size=4096  
    - name: Test SSH connectivity
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22              # make sure you include this if non-standard
        script: |
          echo "👋 Hello from GitHub Actions on $(hostname)"

    - name: Deploy to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: ".next/"  
        target: "/home/ubuntu/PFE-Project/frontend"

    - name: Restart frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /home/ubuntu/PFE-Project/frontend
          pm2 restart frontend || (npm install && pm2 start npm --name "frontend" -- start)