name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test SSH connectivity
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        ssh_options: -o StrictHostKeyChecking=no
        script: echo "SSH OK — $(hostname)"

    - name: Pull, build & restart on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        ssh_options: -o StrictHostKeyChecking=no
        script: |
          set -e
          cd ~/PFE-Project/frontend
          git pull origin main
          npm install --production
          npm run build
          pm2 restart frontend || pm2 start npm --name "frontend" -- start
